apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-admin-api
  labels:
    app: kafka-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-admin-api
  template:
    metadata:
      labels:
        name: kafka-admin-api
    spec:
      containers:
        - name: kafka-admin-api
          image: quay.io/sknot/kafka-admin-api:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_ADMIN_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: KAFKA_ADMIN_OAUTH_ENABLED
              value: "false"
            - name: KAFKA_ADMIN_INTERNAL_TOPICS_ENABLED
              value: "false"
            - name: REST_LOG_LEVEL
              value: "INFO"
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-admin-api-service
  labels:
    app: kafka-admin
spec:
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: kafka-admin-api
  type: ClusterIP
