apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-admin-api
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-admin-api
  template:
    metadata:
      labels:
        name: kafka-admin-api
    spec:
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/sknot/kafka-admin-api:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_ADMIN_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: VERTXWEB_ENVIRONMENT
              value: "dev"
            - name: KAFKA_ADMIN_OAUTH_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-admin-api-service
  labels:
    app: strimzi
spec:
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: kafka-admin-api
  type: ClusterIP